// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;
using microcosm.Views;

namespace microcosm
{
	public partial class SettingListsTableView : NSTableView
	{
        public SettingDispPlanetViewController vc;

		public SettingListsTableView (IntPtr handle) : base (handle)
		{
		}

        public override void MouseDown(NSEvent theEvent)
        {
            base.MouseDown(theEvent);
            vc.ReRender((int)SelectedRow);
        }
	}
}
